- move patch into single file for easier maintenance
Changed files:
    linux-live-config.patch -> 1.4
    linux-live-modprobe.patch -> 1.6
    linux-live-modules.patch -> 1.4
    linux-live-package.patch -> 1.1

diff --git a/linux-live-package.patch b/linux-live-package.patch
--- a/linux-live-package.patch
+++ b/linux-live-package.patch
@@ -1,3 +1,87 @@
+--- linux-live-5.5.0/config	2006-09-27 01:47:53.000000000 +0300
++++ linux-live-5.5.0/config	2006-09-29 15:30:28.000000000 +0300
+@@ -13,11 +13,33 @@
+ 
+ # change this variable if you installed your distro to some directory.
+ # for example ROOT=/tmp/newdir. You may leave it empty, then it defaults to /
+-ROOT=
++ROOT=/vservers/anaconda/root
+ 
+ # kernel version. Change it to "2.6.10" for example, if you are building
+ # LiveCD with a different kernel than the one you are actually running
+-KERNEL="`uname -r`"
++image=$(cd $ROOT; readlink boot/vmlinuz)
++KERNEL="${image#vmlinuz-}"
++
++initrddir="${ROOT%/root}/linux-live-$LINUX_LIVE_VERSION/initrd/kernel-modules/$KERNEL"
++if [ ! -d $initrddir ]; then
++	echo >&2 "Creating $initrd dir"
++	mkdir -p $initrddir
++	for mod in \
++		drivers/cdrom/cdrom \
++		drivers/ide/ide-cd \
++		drivers/ide/ide-core \
++		fs/isofs/isofs \
++		fs/squashfs/squashfs \
++		fs/unionfs \
++		fs/unionfs/unionfs \
++		fs/vfat/vfat \
++		lib/zlib_inflate/zlib_inflate \
++		; do
++		if [ -f $ROOT/lib/modules/$KERNEL/kernel/$mod.ko* ]; then
++			cp -af $ROOT/lib/modules/$KERNEL/kernel/$mod.ko* $initrddir
++		fi
++	done
++fi
+ 
+ # list of directories which will be modularized
+ # You may add 'dev' inthere in the case your distro doesn't have udev installed
+@@ -28,15 +50,15 @@
+-CDDATA=/tmp/live_data_$$
++CDDATA=../live_data_$$
+ 
+ # name of initrd image
+ INITRDIMG=initrd
+ 
+ # Enable debug by setting the following parameter to "logfile.log"
+-DEBUG=/tmp/linux-live-debug.log
++DEBUG=../linux-live-debug.log
+ 
+ # Install/uninstall all scripts from /tools to /usr/sbin and /usr/lib
+ # so the user is able to use all these commands while running his/her Live Linux
+ # Disable if your distro already contains installed linux live tools.
+-INSTALL_TOOLS=1
++INSTALL_TOOLS=0
+ 
+ # where to save resulting livecd ISO image
+-ISO_IMAGE=/tmp/livecd.iso
++ISO_IMAGE=${ISO_IMAGE:-/home/glen/livecd.iso}
+--- linux-live/runme.sh	2006-10-13 15:11:34.000000000 +0300
++++ linux-live/runme.sh	2006-10-13 15:33:24.000000000 +0300
+@@ -10,8 +10,8 @@
+ echo "Changing current directory to $CHANGEDIR"
+ cd $CHANGEDIR
+ 
+-. ./config || exit 1
+-. liblinuxlive || exit 1
++. /etc/linux-live/config || exit 1
++. /usr/lib/liblinuxlive || exit 1
+ 
+ # only root can continue, because only root can read all files from your system
+ allow_only_root
+@@ -19,9 +19,9 @@
+ # search for kernel
+ VMLINUZ=$ROOT/boot/vmlinuz
+ if [ -L "$VMLINUZ" ]; then VMLINUZ=`readlink -f $VMLINUZ`; fi
+-echo -ne "Enter path for the kernel you wanna use [hit enter for $VMLINUZ]: "
+-read NEWKERNEL
+-if [ "$NEWKERNEL" != "" ]; then VMLINUZ="$NEWKERNEL"; fi
++#echo -ne "Enter path for the kernel you wanna use [hit enter for $VMLINUZ]: "
++#read NEWKERNEL
++#if [ "$NEWKERNEL" != "" ]; then VMLINUZ="$NEWKERNEL"; fi
+ if [ "`ls $VMLINUZ 2>>$DEBUG`" = "" ]; then echo "cannot find $VMLINUZ"; exit 1; fi
+ 
+ header "Creating LiveCD from your Linux"
 --- linux-live/initrd/initrd_create	2006-10-13 14:38:45.000000000 +0300
 +++ linux-live-5.5.0/initrd/initrd_create	2006-10-13 16:36:35.000000000 +0300
 @@ -3,11 +3,12 @@
@@ -147,7 +231,7 @@
  
  if [ "$COMPRESS" = 1 ]; then
     debug "gzipping kernel modules"
---- _broken-linux-live-5.5.0/initrd/linuxrc	2006-09-26 18:37:04.000000000 +0300
+--- linux-live-5.5.0/initrd/linuxrc	2006-09-28 01:19:28.000000000 +0300
 +++ linux-live-5.5.0/initrd/linuxrc	2006-09-28 01:19:28.000000000 +0300
 @@ -157,5 +157,8 @@
  fstab_update $UNION
@@ -158,8 +242,18 @@
  # More likely these directories aren't there.
  # Even if they are, this won't hurt.
  # Even if they are, this won't hurt.
---- _broken-linux-live-5.5.0/tools/liblinuxlive	2006-09-26 17:18:28.000000000 +0300
-+++ linux-live-5.5.0/tools/liblinuxlive	2006-09-28 03:14:39.000000000 +0300
+@@ -182,6 +185,9 @@
+ fi
+ 
+ header "linux live end, starting the Linux distribution"
++
++$DEBUGCMD
++
+ pivot_root . $INITRAMDISK
+ exec $CHROOT . sbin/init <dev/console >dev/console 2>&1
+ 
+--- linux-live-5.5.0/tools/liblinuxlive	2006-09-28 03:14:39.000000000 +0300
++++ linux-live-5.5.0/tools/liblinuxlive	2006-09-29 18:04:58.000000000 +0300
 @@ -367,6 +367,13 @@
     list_partition_devices
  }
@@ -174,7 +268,34 @@
  # Find file-path on given device
  # Mounts the device in $1 and returns path if found,
  # else unmounts and exits
-@@ -561,0 +569,13 @@
+@@ -434,10 +441,13 @@
+ #
+ modprobe_essential_modules()
+ {
++   echolog "starting IDE device support"
++   modprobe_module piix
+    echolog "starting loop device support"
+    modprobe_module loop max_loop=255
+    echolog "starting cdrom filesystem support"
+    modprobe_module isofs
++   modprobe_module ide-cd
+    echolog "starting squashfs support"
+    modprobe_module squashfs
+    echolog "starting unionfs support"
+@@ -449,6 +459,12 @@
+    modprobe_module vfat
+    echolog "starting ntfs support"
+    modprobe_module ntfs
++   echolog "starting xfs support"
++   modprobe_module xfs
++   echolog "starting reiserfs support"
++   modprobe_module reiserfs
++   echolog "starting ext3 support"
++   modprobe_module ext3
+    create_block_devices
+ }
+ 
+@@ -561,0 +578,13 @@
 +
 +# create modprobe.conf file $1/etc/modprobe.conf with appropriate ethX module aliases
 +# $1 = root directory (union)
@@ -188,3 +309,14 @@
 +		i=$((i+1))
 +	done
 +}
+--- linux-live-5.5.0/cd-root/isolinux.cfg	2006-05-05 23:25:22.000000000 +0300
++++ linux-live-5.5.0/cd-root/isolinux.cfg	2006-10-03 14:03:53.000000000 +0300
+@@ -7,7 +7,7 @@
+ 
+ label linux
+ kernel boot/vmlinuz
+-append vga=769 max_loop=255 initrd=boot/initrd.gz init=linuxrc load_ramdisk=1 prompt_ramdisk=0 ramdisk_size=4444 root=/dev/ram0 rw
++append vga=769 max_loop=255 initrd=boot/initrd.gz init=linuxrc load_ramdisk=1 prompt_ramdisk=0 ramdisk_size=6444 root=/dev/ram0 rw
+ 
+ label memtest
+ kernel boot/memtest
